### ISSUE TITLE
New Name & Sprite for CCC: The Curio-tainer

### ISSUE THREAD

**Issue by LunarAnticGitHub** [LeoBeliik/ConvenientCuriosContainer#11]
The Curio-tainer, the new restyled version of the Curio Container you know and love for the modern age!
![curiotainer](https://github.com/LeoBeliik/ConvenientCuriosContainer/assets/131813123/fc70d528-b8c6-4b35-911c-9ff236537f7a)

**Comment by LeoBeliik** [comment]
I'll add the texture, I like it, don't think I'll change the name tho, it already has been established as a container so maybe people search for it in jei as that.

**Comment by LunarAnticGitHub** [comment]
Aight

**Comment by LeoBeliik** [comment]
Could you make a bigger version for the CF logo? it has to be at least 400x400px

**Comment by LunarAnticGitHub** [comment]
I'll try

**Comment by LeoBeliik** [comment]
Only if it's not much bother, I don't want to make you do unnecessary extra work.
If you don't want to do it you can always release the icon (and name) as a texture pack in cf, I won't mind.

**Comment by LunarAnticGitHub** [comment]
I'm just not at home rn, I'll resize it in Piskell
