### ISSUE TITLE
[1.21.1][Neoforge] Crash when opening the container

### ISSUE THREAD

**Issue by ffuentesm** [LeoBeliik/ConvenientCuriosContainer#12]
### Convenient Curios container version

convenientcurioscontainer-2.0.jar

### NeoForge version

21.1.51

### Additional mod(s) version (If bug is due incompatibility)

I am not sure if this is relevant to the issue, but I am using Accessories with the Curious layers addon
accessories_cclayer-9.0.5-beta.11+1.21
accessories-neoforge-1.0.0-beta.34+1.21 

### Describe the bug

Game crashes when I attempt to pen the container 

### Steps to reproduce

Open the container

### Crashlog

https://pastebin.com/GSNbR6BX

**Comment by LeoBeliik** [comment]
The mod depends on internals from the curio api that accessories doesn't provide, for now it's incompatible with it. 
I want to implement some compat with accessories eventually, but I don't know if it will be possible.
