### ISSUE TITLE
🐞 Some items create ghost items inside the CCC on servers

### ISSUE THREAD

**Issue by LeoBeliik** [LeoBeliik/ConvenientCuriosContainer#7]
### Convenient Curios container version

1.11

### Forge version

1.19+ & 1.18

### Describe the bug

~~This is due to the problem of some items adding new curios slots, this mod is going thru a rewrite and this will be fixed in v2.0 **which** most probably **will land on minecraft 1.20.**~~

Update: Curios update added a way to fix this so I may try to implement a fix for 1.18+, no promises  

### Additional context

it just a visual bug.

**Comment by Yourname942** [comment]
When you say ghost items, can you elaborate? Do you mean it duplicates the item in all aspects, does it just look like the item remains in the container? Something else? Thank you!

**Comment by LeoBeliik** [comment]
It looks like the item gets duped but it disappears as soon as you close the Inv or click the item 
Lastest curios version added a way to deal with this so I may fix it for 1.18+ versions if I find time
