### ISSUE TITLE
🐞 SlotModifiersUpdatedEvent (Startup Crash)

### ISSUE THREAD

**Issue by border999** [LeoBeliik/ConvenientCuriosContainer#8]
### Convenient Curios container version

1.12

### Forge version

1.18.2-40.2.0

### Describe the bug

Startup Crash

### Crashlog

https://gist.github.com/border999/21c50118f6a3afdfb9ff794e44e55f2f

**Comment by LeoBeliik** [comment]
Update Curios API to 1.18.2-5.0.8.0
