### ISSUE TITLE
Configuration for more slots

### ISSUE THREAD

**Issue by chocolatechipcats** [LeoBeliik/ConvenientCuriosContainer#9]
I have more trinkets than there's room for in the container. It would be helpful to configure how many slots are available.

Since I'm still on 1.19.2, a backport for this feature would be nice, but don't worry about it. 

Thanks in advance.

**Comment by LeoBeliik** [comment]
Currently this would be out of the scope of the mod, you can use multiple ccc to accomplish this tho, yeah is not as convenient but call it *balance*
Said that, I want to change the core of this mod eventually (it was supposed to be a rework for 1.20 but I didn't have time)
so for now I'll close this as not planned, but I'll take it in consideration for the future.

**Comment by chocolatechipcats** [comment]
When re-working it, another alternative would be able to upgrade the container (similar to the various icon chest/barrel mods available). Thanks.
